version: '2'

services:
  db:
    image: postgres:9.6
    hostname: db
    environment:
      - POSTGRES_USER=bot
      - POSTGRES_PASSWORD=bot
      - POSTGRES_DB=intellect_bot
    volumes:
      - db:/var/lib/postgresql
    ports:
      - "5435:5432"

  redis:
    image: redis:3.0
    hostname: redis
    ports:
      - "6379"


  web:
    build:
      context: ../intellect_bot
      dockerfile: Dockerfile
    hostname: web
    command: ./run_django.bash
    environment:
      - DEBUG
    volumes:
      - .:/usr/src/app
      - static:/var/www/static
      - media:/var/www/media
    ports:
      - "8004:8000"
    links:
      - db
      - redis

    depends_on:
      - db
      - redis

  celery:
    build:
      context: ../intellect_bot
      dockerfile: Dockerfile
    environment:
      - DEBUG
    command: ./run_celery.bash
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
      - media:/var/www/media
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
  nginx:
    image: nginx:1.13
    volumes:
      - ./bot_mother/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/sarafankabot.ru/fullchain.pem:/etc/letsencrypt/live/sarafankabot.ru/fullchain.pem
      - /etc/letsencrypt/live/sarafankabot.ru/privkey.pem:/etc/letsencrypt/live/sarafankabot.ru/privkey.pem
    volumes_from:
      - web
    ports:
      - "80"
      - "443:443"
    links:
      - web

volumes:
  db:
  static:
  media: